#ifndef MACHINE_LAN_H
#define MACHINE_LAN_H

#define _ASSN_ "ASSN"
#define _MOVE_ "MOVE"
#define _ASSV_ "ASSV"
#define _COMP_ "COMP"
#define _EQAL_ "EQAL"
#define _NEQL_ "NEQL"
#define _CJMP_ "CJMP"
#define _JUMP_ "JUMP"
#define _HALT_ "HALT"
#define _PUTC_ "PUTC"
#define _PUTS_ "PUTS"
#define _PUTI_ "PUTI"
#define _ADDN_ "ADDN"
#define _ADDO_ "ADDO"
#define _MULT_ "MULT"
#define _DIVI_ "DIV"
#define _GETC_ "GETC"
#define _GETS_ "GETS"
#define _GETI_ "GETI"
#define _PUSH_ "PUSH"
#define _PULL_ "PULL"
#define _ANDC_ "ANDC"
#define _ORLC_ "ORLC"
#define _NOTC_ "NOTC"

#define _MKFL_ "MKFL"
#define _MKDR_ "MKDR"
#define _SPCE_ "SPCE"
#define _OPNF_ "OPNF"
#define _REDF_ "REDF"
#define _RUNF_ "RUNF"

#endif MACHINE_LAN_H